### ISSUE TITLE
App is not working

### ISSUE THREAD

**Issue by Tjeempie69** [magtimmermans/com.cyclone-software.holidays#12]
App is not working since 2 days (4-6-2024). I have restarted the app and also restarted the total Homey system.

![image](https://github.com/magtimmermans/com.cyclone-software.holidays/assets/171907267/90e09dbe-c14a-4f7d-9f63-0d35df83ed37)

**Comment by magtimmermans** [comment]
I will take a look.

**Comment by Tjeempie69** [comment]
Vast bedankt


Met vriendelijke groet,

John Lesage

Logic Vision

Op 6 jun 2024 om 12:43 heeft magtimmermans ***@***.***> het volgende geschreven:

﻿

I will take a look.

**Comment by magtimmermans** [comment]
Fixed.
https://homey.app/a/com.cyclone-software.holidays/test/

**Comment by Tjeempie69** [comment]
Hi There,

I've checked the flow again and it is still not working, see screenshot below. I have reset the app and also restarted the Homey.
Please advice, I could not find the GItHub issue, therefor I send this email,

[cid:da49fa94-0d16-41fd-9c60-26e444bc3dae]

Met vriendelijke groet,

John Lesage
________________________________
Van: magtimmermans ***@***.***>
Verzonden: vrijdag 7 juni 2024 14:15
Aan: magtimmermans/com.cyclone-software.holidays ***@***.***>
CC: Tjeempie69 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [magtimmermans/com.cyclone-software.holidays] App is not working (Issue #12)


Closed #12<https://github.com/magtimmermans/com.cyclone-software.holidays/issues/12> as completed.

**Comment by magtimmermans** [comment]
Hi,

I cannot open the image.


Marcel Timmermans
Send from my iphone


Op 7 jun 2024 om 16:00 heeft Tjeempie69 ***@***.***> het volgende geschreven:

﻿

Hi There,

I've checked the flow again and it is still not working, see screenshot below. I have reset the app and also restarted the Homey.
Please advice, I could not find the GItHub issue, therefor I send this email,

[cid:da49fa94-0d16-41fd-9c60-26e444bc3dae]

Met vriendelijke groet,

John Lesage
________________________________
Van: magtimmermans ***@***.***>
Verzonden: vrijdag 7 juni 2024 14:15
Aan: magtimmermans/com.cyclone-software.holidays ***@***.***>
CC: Tjeempie69 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [magtimmermans/com.cyclone-software.holidays] App is not working (Issue #12)


Closed #12<https://github.com/magtimmermans/com.cyclone-software.holidays/issues/12> as completed.

**Comment by Tjeempie69** [comment]
Good Morning,

[cid:c1867e69-c6d9-4d6c-8604-face6c5f78a1]

This is the screenshot, it crashes at checking for holidays. Error message is below,

[IMG_5302.jpg]

Met vriendelijke groet,

John Lesage
________________________________
Van: magtimmermans ***@***.***>
Verzonden: vrijdag 7 juni 2024 16:57
Aan: magtimmermans/com.cyclone-software.holidays ***@***.***>
CC: Tjeempie69 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [magtimmermans/com.cyclone-software.holidays] App is not working (Issue #12)


Hi,

I cannot open the image.


Marcel Timmermans
Send from my iphone


Op 7 jun 2024 om 16:00 heeft Tjeempie69 ***@***.***> het volgende geschreven:

﻿

Hi There,

I've checked the flow again and it is still not working, see screenshot below. I have reset the app and also restarted the Homey.
Please advice, I could not find the GItHub issue, therefor I send this email,

[cid:da49fa94-0d16-41fd-9c60-26e444bc3dae]

Met vriendelijke groet,

John Lesage
________________________________
Van: magtimmermans ***@***.***>
Verzonden: vrijdag 7 juni 2024 14:15
Aan: magtimmermans/com.cyclone-software.holidays ***@***.***>
CC: Tjeempie69 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [magtimmermans/com.cyclone-software.holidays] App is not working (Issue #12)


Closed #12<https://github.com/magtimmermans/com.cyclone-software.holidays/issues/12> as completed.

**Comment by magtimmermans** [comment]
Please reopen the case  as I do not see the images.
Marcel Timmermans
Send from my iphone


Op 10 jun 2024 om 08:54 heeft Tjeempie69 ***@***.***> het volgende geschreven:

﻿

Good Morning,

[cid:c1867e69-c6d9-4d6c-8604-face6c5f78a1]

This is the screenshot, it crashes at checking for holidays. Error message is below,

[IMG_5302.jpg]

Met vriendelijke groet,

John Lesage
________________________________
Van: magtimmermans ***@***.***>
Verzonden: vrijdag 7 juni 2024 16:57
Aan: magtimmermans/com.cyclone-software.holidays ***@***.***>
CC: Tjeempie69 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [magtimmermans/com.cyclone-software.holidays] App is not working (Issue #12)


Hi,

I cannot open the image.


Marcel Timmermans
Send from my iphone


Op 7 jun 2024 om 16:00 heeft Tjeempie69 ***@***.***> het volgende geschreven:

﻿

Hi There,

I've checked the flow again and it is still not working, see screenshot below. I have reset the app and also restarted the Homey.
Please advice, I could not find the GItHub issue, therefor I send this email,

[cid:da49fa94-0d16-41fd-9c60-26e444bc3dae]

Met vriendelijke groet,

John Lesage
________________________________
Van: magtimmermans ***@***.***>
Verzonden: vrijdag 7 juni 2024 14:15
Aan: magtimmermans/com.cyclone-software.holidays ***@***.***>
CC: Tjeempie69 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [magtimmermans/com.cyclone-software.holidays] App is not working (Issue #12)


Closed #12<https://github.com/magtimmermans/com.cyclone-software.holidays/issues/12> as completed.
